name: C# Autograding

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet build
    - name: Test
      run: |
        output=$(dotnet run)
        if [ "$output" == "Hello World!" ]; then
          echo "Test passed!"
        else
          echo "Test failed."
          exit 1
        fi
